server:
  address: 0.0.0.0
  port: 8080
  allowed_origin: "*"
  reload: false
  workers_count: 1
  proxy_headers: true
  forwarded_allow_ips: "*"
  uvicorn_log_level: info
  max_upload_files: 10
  log_level: info
  enable_datadog: false
  logger:
    level: info
    log_access: true
    log_file: "testlog"
    log_file_count: 5
    log_file_size: 10485760

postgres:
  enabled: true
  address: 0.0.0.0
  db_name: service_platform
  username: local
  password: local
  port: 5432

redis:
  enabled: false
  address: 0.0.0.0
  port: 30001
  username: "local"
  password: "local"
  base: 0

datadog:
  enabled: false

jwt:
  secret_key_base64: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcTlkdUtyZDlyTVdoaERjcHdoVys3RXpjcW40Ylo1R21zQnNERUhnNTEwc3FUYnkrCmhqN2RlcFpBdVdocnFiQ0QyaFN6L2dqWjlxVVpIZ1M4bm1RaXAxTTNpMWVnVkFiQ20vdXp3UUFnZmpQNXhaaXQKcm12clROU3Y4TVR3WnhmMFROZUJOUlRtaU1KOTVnUm1VMUc5VlJPUGRuWDZjOC80VzVLcHBzRksyZlorY3ZUdAprcFNhZUFvRFZnWml4QmpwN0pJdjJERjREcnNvN2VRcXdtRnRNd2FoclBjeVBGdmVnTzIyYWFlNG1rZHBJTG85CkkxalNtUzRqQW12cVJvY1JGVlhvR3ZVUmx0MG1iajhCM3UwVmJsVDdYVFM3ZjFKQmlYd3pac3hjQmswSmN3WVkKb2l6WVVFdHdudFBrTHl5anZzNklSakNBU2E1NTRocmNEbkpFR1lkMHhwQTcwY3RlN2tGaE1UakpoUHRsdXF1UAp3d2c5bjY1cmptYzhOMGZlSCtTZk1IZkx4RlBVSE80aE1udEcxcEdGaDNXVWtnRWtibmZzN0RmZzVOdG4yWWJMCjFjQ3hKRjZCWG1sTGIyRFk0cnhOYzRoano1ZG9sVU1CREFIcVVyR25yZnZCc2J5VUFtZHZQVjhFSjQwdlM1ZEIKWlQ1RjZpcnZpWVlVV2Z0WWtRZ3FvMjhhZWhlQlU0NHgrd3FuZENhTXFJbmw0c2c1bzBaVkpsWnVyckZHSndOUgpySjl0N0JQSWRkOEdhTzdXYlBrWG9KY3hGQnNzaGg3ZHF1K1dlbkgxVDVvSEsyL3VIKzc4SENvN3dKcVhOdDZDCnVWbTdJWGsxWnVoYzhmQ2VqeG1ZaHRZTjBIYlN4bWlhV0FpZUFuR3podGhGVUprR1E5S1ZkV3hMaGVzQ0F3RUEKQVFLQ0FnQXI4V2dycGthT0F1L2R0cG1JRnpWK2lkMDRBQTJUKzR3THBxeXU3bitrRFlXZzRXNDdPQ0k4OGVWVgpSRjJieEJiRGt0M0FUWlVuWEdyQzRXVTJmOWJZd1JBSUl2MU4zM2l1bUx3TDA3TjdjbUVoNVh3c2lVNWZsRmYxCmt2Y0M5ZjQwRkR2blRoUHh6d0tRNm5rY1AxL1NQTEZJRXIxY0ZrZWxheWpWQ3NMUVlCZFA0RkJNVnBIMXRtSEsKQXRJSTRYSVlXLzIrSkZCV1BBZ29aVnVGMzVJa0pVTDh6eTNhZjRlem9wWXVDSVROZHd0c0loUDJVUVZ4eEhtUgphZlU3MmRoRmczVmFSMmNiRkN4NnJzUVV0TDN4Tyt3WGxwK0gzSW9EMVczemtMakxwN0dONTNZdktwYWFXZUJQCnpWR2h1cUdZN29tc29VUjlFdy82QVBKYkExOWtXRjkyaHBQcHlrNTNKRGZjYll1RzB0a2dOUGQ4ZDM0NUNiNUcKRzA5dHc1OGV1Uk4wNFQ2ZGZrUFNicGo0aHgyK1NhNEpBWUZoemlaWmtqTHJUTHFveElDQk93QlpoVU9FUjBpUApUUVFWUWFMVEFVaUJYQzUzVitETTQ3ZHBvd3ZyOG9aUEtKS1ZVUEI2U2lFakF3QlJOUHE2WG9iRHRIMCtxc2ZjCjRCMmZuR3RYNHdhT0s1a21HWjZJbXFtOGNPUFpHc0VqSGFCb1Z2WmtCVlJSQy9Qc0prNW85VGJuRmF1cWwwRHEKR2c5WGdjUE5CUWpqZ0ZiNDZPL0ZIWDUwMkc4emcyVVE3UCtKcTFYWVg2bCtGa3paU2tGeHM4Rks1YVI4bE1OKwo0U0dqTnpUTlVCSmowU0pEMXA4S0psYnErOHZ4WWR4R3VpeGVCSjMzN0pPc1Vra1V3UUtDQVFFQTM4QzhUL21DCjQ5VEw3V2NRbFpBVEQxenBuTWMzMTBOUkJvQ3lDSW9za0dvRnZjYjFuVW1IQ0N2SmhMRVNWY3VyR1RQanNBZmoKTTZoUHRSNTN3UUphSGIwYnM1eU93WFdicVRXSWhrc2g5MGNCQ0hicDdTQlZLNHBuci82MU13Nzc5YndDaEh4SgpiRTEzRFErSXMwZDMxRkR6QVZsMEd1MXROQjdOdlJ4V0tOek5nbEFpL3RSbGloYkVMM0VNNm5RQkZIQ3h4bVdHCnBtQTl2bWExNnVNTlJkYmFZclNTNmhNNnlNWHRpcWdYWEpRM0ZGK1YyY09YUGVYd3ZhZXFKN0JSNDlVMEZ5Y0cKbnNvdG9VQ0NtK0FaTFFTN2wyNVVDbFBhNFZyVFQxWHhUN1FqMGE1LytpSmJOOXR4MHdUWjB2cVFjK2ZDWi9DSgpVSjhORzJOOEkyRTRJUUtDQVFFQXhKdHl2ODA3Yk14TTJCL1JOdmZ3UmpEQ3lnU3hCMXRyZ3ZvUDVteWRPTktMClpuNlFhbDFhZVN4ZTdFK3R3MWtWa3V4MTRFNWF3OFJ3SThoR3JKUUJmVHMwYmpTaGlrRFBucGw0cHY1Zm4vckEKcVFQcExJemlObGM5S1pxOGNZQWRSc3psRGsxOVpxQm41NlkyOTdvZDhkaS8rdzY0KzE3cXErV1c5TmpySHd0WQovSnpndTNCaDVTbmhkUDFJRnBLMDhiakVndVRUbUdQbUQvQXN2djdLUDB1d09vUGtPSGR6dkFaUXZpeVdzTlhSCjI0WklLS05uOEVDcjBMSjZGWkxZNm1FOG5Lc29tM0NLcXZIMy9kcWRLVStEMUMycW9YekhzbUxPeTZoR1NXTTEKYzlIMFdrTFpUU2lvZUl0Z01xRmRkdHZJUURKdnZXbXFNR2xWVWRDTWl3S0NBUUJaN05rQi8xSm1oR2h0QWlYOQpKZ2t5L0hGN0srbTZYdmlhZDNDVjFBcHpBOWxJMjBSdE1WYk9wdUozckw2a3NwVVNMUE9PRksxd1htMmlhaHRRCis4UUIvYlc3YXVsSXdSNk5VOUdKdjNwb0tpWTFJNjJDT3FOZ08yRE9yN3hkUitGbGNtbEVtN3JhaHd1WXVTeUUKZU8yazY5K3VKQ2h3aGdtRWovaTV6MENsYlpBK2xqeHFWQ3gyNGcxNHo2T1VPb2tRa1BZeHVTM3pnZXh1c0ZMZQprdUFMdUh6T2ZLb3EzdzJhRVVvVmx0YkV3MkNibElyaUdTU1lvT2d2SU1wVzV4c1NTT2FGZzQ2NmxLRGdGTkFwCkcxaWk2aXNHZ2pYT2JNTWtITitlRy9rK3dqUS9HaldlN3QzZ1JoYXA2MklyMDczb2h6VnZscEZwVUhMeEZmdVgKTUlSaEFvSUJBREZORWI5TEJhWElyVlJjMWlmRWtMbnBMRTlnVWN3WWZxTS9kWkZBbDBSU2Q2WmlBbkRKckJCSwpzaHJyK0JUT1YveVowdzFHV0xoU29CUTQrby80SlU5ejh6ZlhkdEttWWVuUmJsSGg0N1RJT2x1bm9XY01oUVUvClp4VHh1bU56enVPY0thd21mbFduejZabEpjK0ZHbEUxR3g4bmwvZGcyOVB6SktHTmE1aERUak02VzVobEhBZE4KTXo0VTdXakxyUmdZVHg3THBzdkY4VUQ1NXg2VjRiMXhpMldCQVUrdmxKUUh1V09XNXNxOU0zeXE5WmxMTUpzcwpmR2srK0NKRXlxUXJjZm1QYWdWZ2VVVlltK2xLVXJLelA4bUxFZ2lnczZybDRCbHR2d0pVSUdsRXN0T1hnOG8zCmNkZVlpNnptamZ0cUxaTDdrczJhbTVTOE5Tcm84dlVDZ2dFQkFNNFZFMlhPM3R5eVM5eitzZFprSDZ2LzJRbXcKYkIrUkIzZVdmTHVvSnJ5cmR5YnVDSjd0N1lEVDgxQ3VCMldDRUFTaDk3QjBhNi84S1FaSEdjS3VPUGM1RnhUQgpwSjRoWmhnSjN1Q3RzUnJQbU9CU09uMWhxaXhTNk04QnQ3LzdpdHFZVE04eEZHY0FPSG41RXMrZ2NkZFRvenlFCkpVMEJoTHdaZFI1eDVrcVlTRTI5UmxNaG5PanNNL05wYzUvT2F0ZW5ZemZ5Q3IyZElQY2JDaElIZEkrRHBESUYKTTdvdThBYy93REkzMGw0R2pjdUNYYk84K0YrRThkQTdMSU5VYlllODRBT0lTMzJxemQzckNVMUlsQXU2dytGZwprUTJhb2pFNFNWV2dNei9oTDBQNmtob01vVHJlSDhWQTVCTlBVbUNGWnY1cEUrYU1abyt2b3B0blhhcz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K"
  public_key_base64: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFxOWR1S3JkOXJNV2hoRGNwd2hXKwo3RXpjcW40Ylo1R21zQnNERUhnNTEwc3FUYnkraGo3ZGVwWkF1V2hycWJDRDJoU3ovZ2paOXFVWkhnUzhubVFpCnAxTTNpMWVnVkFiQ20vdXp3UUFnZmpQNXhaaXRybXZyVE5TdjhNVHdaeGYwVE5lQk5SVG1pTUo5NWdSbVUxRzkKVlJPUGRuWDZjOC80VzVLcHBzRksyZlorY3ZUdGtwU2FlQW9EVmdaaXhCanA3Skl2MkRGNERyc283ZVFxd21GdApNd2FoclBjeVBGdmVnTzIyYWFlNG1rZHBJTG85STFqU21TNGpBbXZxUm9jUkZWWG9HdlVSbHQwbWJqOEIzdTBWCmJsVDdYVFM3ZjFKQmlYd3pac3hjQmswSmN3WVlvaXpZVUV0d250UGtMeXlqdnM2SVJqQ0FTYTU1NGhyY0RuSkUKR1lkMHhwQTcwY3RlN2tGaE1UakpoUHRsdXF1UHd3ZzluNjVyam1jOE4wZmVIK1NmTUhmTHhGUFVITzRoTW50RwoxcEdGaDNXVWtnRWtibmZzN0RmZzVOdG4yWWJMMWNDeEpGNkJYbWxMYjJEWTRyeE5jNGhqejVkb2xVTUJEQUhxClVyR25yZnZCc2J5VUFtZHZQVjhFSjQwdlM1ZEJaVDVGNmlydmlZWVVXZnRZa1FncW8yOGFlaGVCVTQ0eCt3cW4KZENhTXFJbmw0c2c1bzBaVkpsWnVyckZHSndOUnJKOXQ3QlBJZGQ4R2FPN1diUGtYb0pjeEZCc3NoaDdkcXUrVwplbkgxVDVvSEsyL3VIKzc4SENvN3dKcVhOdDZDdVZtN0lYazFadWhjOGZDZWp4bVlodFlOMEhiU3htaWFXQWllCkFuR3podGhGVUprR1E5S1ZkV3hMaGVzQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
  algorithm: "RS512"
  expiration_time: 1440
  refresh_expiration_time: -1

aws:
  region: "us-west-2"
  s3_bucket: "local"
  sqs:
    localstack: true
    workers:
      example_worker:
        url: "local"
        number_of_consumers: 0

google:
  api_url: "https://www.googleapis.com"
  oauth_url: "https://oauth2.googleapis.com"
  client_id: local
  client_secret: local
  redirect_uri: "http://localhost:5173/google/callback"

linkedin:
  api_url: "https://api.linkedin.com"
  oauth_url: "https://www.linkedin.com"
  client_id: local
  client_secret: local
  redirect_uri: "http://localhost:5173/linkedin/callback"

zoom:
  zoom_url: "https://zoom.us"
  api_url: "https://api.zoom.us"
  client_id: local
  client_secret: local
  redirect_uri: "https://localhost:5173/zoom/callback"

auth0:
  client_id: local
  client_secret: local
  redirect_uri: "http://localhost:5173/auth0/callback"
  base_url: "https://<domain>.us.auth0.com"
