version: '3.6'
services:
  db:
    image: postgis/postgis:16-master
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: db_py
      POSTGRES_HOST_AUTH_METHOD: password
    networks:
    - spartan_net
    command: postgres -N 500
    platform: linux/amd64
    ports:
    - "5432:5432"
    volumes:
    - type: tmpfs
      target: /var/lib/postgresql-py/data

  redis-cluster:
    image: channguyen/redis-cluster:latest
    restart: always
    networks:
    - spartan_net
    ports:
    - "30001:30001"
    - "30002:30002"
    - "30003:30003"
    - "30004:30004"
    - "30005:30005"
    - "30006:30006"

networks:
  spartan_net:
    name: spartan_net
