version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: service_platform_py:${service_platform_py_VERSION:-latest}
    restart: always
    networks:
    - default
    ports:
    - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    environment:
      RELOAD: false
      PORT: 8000
      REDIS_HOST: service_platform_py-redis
      ENVIRONMENT: production
      HOST: 0.0.0.0

  taskiq-worker:
    <<: *main_app
    ports: []
    labels: []
    command:
    - taskiq
    - worker
    - service_platform_py.tkq:broker
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "service_platform_py-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
