name: Testing service_platform_py

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      service_platform_py-db:
        image: postgis/postgis:16-master
        env:
          POSTGRES_PASSWORD: local
          POSTGRES_USER: local
          POSTGRES_DB: db_py
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Install flyway
      run: |
        sudo snap install flyway
        sudo ln -s /snap/bin/flyway /usr/local/bin/flyway

    - name: Run pytest check
      run: poetry run pytest
